version: '3'
services:
  php:
    build: php
    volumes:
      - ./project:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - CONF_XDEBUG_CLIENT_IP=${CONF_XDEBUG_CLIENT_IP}
      - CONF_XDEBUG_CLIENT_PORT=${CONF_XDEBUG_CLIENT_PORT}
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${CONF_MYSQL_PASSWORD}
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - "${CONF_MYSQL_PORT}:3306"
  nginx:
    image: nginx
    ports:
      - "${CONF_NGINX_MAIN_PORT}:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./project:/var/www/html